
#ifndef DSALIB_BINARY_SEARCH_H
#define DSALIB_BINARY_SEARCH_H
#include <algorithm>
#include <climits>
#include <numeric>
#include <stdexcept>
#include <vector>
namespace dsalib {
class BinarySearch {
public:
    static int search_sorted(const std::vector<int>& a,int target){int l=0,r=(int)a.size()-1;while(l<=r){int m=l+(r-l)/2;if(a[m]==target)return m;if(a[m]<target)l=m+1;else r=m-1;}return -1;}
    static int lower_bound_index(const std::vector<int>& a,int target){int l=0,r=(int)a.size();while(l<r){int m=l+(r-l)/2;if(a[m]<target)l=m+1;else r=m;}return l;}
    static int upper_bound_index(const std::vector<int>& a,int target){int l=0,r=(int)a.size();while(l<r){int m=l+(r-l)/2;if(a[m]<=target)l=m+1;else r=m;}return l;}
    static int first_occurrence(const std::vector<int>& a,int target){int i=lower_bound_index(a,target);return i<(int)a.size()&&a[i]==target?i:-1;}
    static int last_occurrence(const std::vector<int>& a,int target){int i=upper_bound_index(a,target)-1;return i>=0&&a[i]==target?i:-1;}
    static int search_rotated(const std::vector<int>& a,int target){int l=0,r=(int)a.size()-1;while(l<=r){int m=l+(r-l)/2;if(a[m]==target)return m;if(a[l]<=a[m]){if(a[l]<=target&&target<a[m])r=m-1;else l=m+1;}else{if(a[m]<target&&target<=a[r])l=m+1;else r=m-1;}}return -1;}
    static int find_peak(const std::vector<int>& a){if(a.empty())return -1;int l=0,r=(int)a.size()-1;while(l<r){int m=l+(r-l)/2;if(a[m]<a[m+1])l=m+1;else r=m;}return l;}
    static bool search_matrix(const std::vector<std::vector<int> >& mat,int target){ if(mat.empty()||mat[0].empty()) return false; int rows=mat.size(), cols=mat[0].size(); int l=0,r=rows*cols-1; while(l<=r){int m=l+(r-l)/2;int v=mat[m/cols][m%cols]; if(v==target)return true; if(v<target)l=m+1; else r=m-1;} return false; }
    static int koko_bananas(const std::vector<int>& piles,int h){int l=1,r=*std::max_element(piles.begin(),piles.end()),ans=r;while(l<=r){int m=l+(r-l)/2;long long hrs=0;for(size_t i=0;i<piles.size();++i)hrs+=(piles[i]+m-1)/m;if(hrs<=h){ans=m;r=m-1;}else l=m+1;}return ans;}
    static int ship_packages(const std::vector<int>& w,int days){int l=*std::max_element(w.begin(),w.end()),r=std::accumulate(w.begin(),w.end(),0),ans=r;while(l<=r){int m=l+(r-l)/2;if(can_ship(w,days,m)){ans=m;r=m-1;}else l=m+1;}return ans;}
    static int split_array(const std::vector<int>& nums,int k){int l=*std::max_element(nums.begin(),nums.end()),r=std::accumulate(nums.begin(),nums.end(),0),ans=r;while(l<=r){int m=l+(r-l)/2;if(parts(nums,m)<=k){ans=m;r=m-1;}else l=m+1;}return ans;}
    static int minimum_bouquets(const std::vector<int>& bloom,int m,int k){ if((long long)m*k>(long long)bloom.size()) return -1; int l=*std::min_element(bloom.begin(),bloom.end()),r=*std::max_element(bloom.begin(),bloom.end()),ans=-1; while(l<=r){int mid=l+(r-l)/2; if(can_make(bloom,m,k,mid)){ans=mid;r=mid-1;}else l=mid+1;} return ans; }
    static int smallest_divisor(const std::vector<int>& nums,int threshold){int l=1,r=*std::max_element(nums.begin(),nums.end()),ans=r;while(l<=r){int m=l+(r-l)/2;long long sum=0;for(size_t i=0;i<nums.size();++i)sum+=(nums[i]+m-1)/m;if(sum<=threshold){ans=m;r=m-1;}else l=m+1;}return ans;}
private:
    static bool can_ship(const std::vector<int>& w,int d,int cap){int used=1,load=0;for(size_t i=0;i<w.size();++i){if(load+w[i]>cap){++used;load=0;}load+=w[i];}return used<=d;}
    static int parts(const std::vector<int>& a,int cap){int p=1;long long s=0;for(size_t i=0;i<a.size();++i){if(s+a[i]>cap){++p;s=0;}s+=a[i];}return p;}
    static bool can_make(const std::vector<int>& b,int m,int k,int day){int made=0,run=0;for(size_t i=0;i<b.size();++i){if(b[i]<=day){if(++run==k){++made;run=0;}}else run=0;}return made>=m;}
};
}
#endif
// binary_search reference note 0001: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0002: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0003: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0004: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0005: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0006: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0007: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0008: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0009: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0010: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0011: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0012: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0013: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0014: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0015: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0016: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0017: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0018: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0019: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0020: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0021: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0022: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0023: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0024: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0025: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0026: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0027: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0028: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0029: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0030: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0031: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0032: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0033: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0034: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0035: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0036: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0037: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0038: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0039: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0040: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0041: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0042: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0043: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0044: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0045: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0046: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0047: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0048: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0049: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0050: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0051: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0052: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0053: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0054: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0055: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0056: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0057: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0058: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0059: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0060: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0061: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0062: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0063: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0064: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0065: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0066: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0067: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0068: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0069: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0070: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0071: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0072: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0073: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0074: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0075: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0076: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0077: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0078: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0079: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0080: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0081: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0082: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0083: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0084: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0085: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0086: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0087: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0088: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0089: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0090: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0091: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0092: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0093: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0094: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0095: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0096: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0097: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0098: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0099: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0100: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0101: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0102: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0103: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0104: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0105: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0106: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0107: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0108: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0109: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0110: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0111: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0112: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0113: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0114: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0115: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0116: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0117: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0118: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0119: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0120: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0121: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0122: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0123: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0124: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0125: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0126: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0127: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0128: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0129: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0130: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0131: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0132: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0133: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0134: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0135: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0136: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0137: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0138: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0139: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0140: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0141: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0142: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0143: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0144: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0145: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0146: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0147: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0148: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0149: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0150: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0151: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0152: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0153: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0154: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0155: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0156: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0157: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0158: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0159: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0160: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0161: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0162: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0163: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0164: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0165: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0166: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0167: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0168: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0169: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0170: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0171: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0172: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0173: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0174: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0175: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0176: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0177: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0178: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0179: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0180: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0181: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0182: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0183: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0184: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0185: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0186: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0187: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0188: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0189: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0190: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0191: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0192: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0193: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0194: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0195: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0196: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0197: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0198: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0199: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0200: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0201: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0202: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0203: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0204: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0205: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0206: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0207: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0208: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0209: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0210: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0211: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0212: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0213: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0214: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0215: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0216: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0217: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0218: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0219: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0220: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0221: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0222: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0223: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0224: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0225: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0226: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0227: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0228: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0229: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0230: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0231: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0232: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0233: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0234: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0235: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0236: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0237: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0238: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0239: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0240: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0241: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0242: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0243: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0244: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0245: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0246: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0247: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0248: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0249: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0250: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0251: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0252: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0253: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0254: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0255: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0256: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0257: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0258: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0259: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0260: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0261: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0262: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0263: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0264: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0265: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0266: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0267: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0268: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0269: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0270: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0271: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0272: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0273: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0274: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0275: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0276: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0277: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0278: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0279: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0280: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0281: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0282: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0283: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0284: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0285: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0286: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0287: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0288: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0289: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0290: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0291: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0292: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0293: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0294: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0295: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0296: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0297: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0298: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// binary_search reference note 0299: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// dsalib extended reference binary_search_h 0001: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0002: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0003: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0004: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0005: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0006: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0007: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0008: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0009: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0010: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0011: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0012: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0013: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0014: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0015: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0016: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0017: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0018: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0019: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0020: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0021: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0022: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0023: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0024: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0025: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0026: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0027: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0028: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0029: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0030: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0031: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0032: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0033: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0034: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0035: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0036: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0037: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0038: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0039: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0040: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0041: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0042: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0043: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0044: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0045: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0046: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0047: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0048: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0049: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0050: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0051: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0052: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0053: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0054: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0055: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0056: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0057: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0058: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0059: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0060: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0061: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0062: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0063: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0064: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0065: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0066: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0067: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0068: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0069: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0070: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0071: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0072: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0073: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0074: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0075: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0076: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0077: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0078: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0079: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0080: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0081: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0082: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0083: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0084: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0085: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0086: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0087: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0088: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0089: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0090: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0091: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0092: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0093: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0094: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0095: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0096: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0097: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0098: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0099: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0100: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0101: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0102: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0103: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0104: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0105: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0106: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0107: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0108: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0109: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0110: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0111: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0112: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0113: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0114: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0115: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0116: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0117: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0118: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0119: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0120: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0121: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0122: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0123: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0124: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0125: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0126: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0127: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0128: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0129: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0130: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0131: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0132: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0133: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0134: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0135: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0136: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0137: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0138: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0139: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0140: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0141: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0142: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0143: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0144: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0145: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0146: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0147: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0148: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0149: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0150: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0151: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0152: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0153: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0154: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0155: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0156: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0157: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0158: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0159: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0160: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0161: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0162: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0163: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0164: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0165: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0166: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0167: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0168: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0169: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0170: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0171: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0172: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0173: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0174: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0175: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0176: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0177: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0178: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0179: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0180: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0181: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0182: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0183: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0184: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0185: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0186: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0187: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0188: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0189: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0190: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0191: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0192: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0193: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0194: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0195: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0196: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0197: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0198: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0199: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0200: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0201: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0202: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0203: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0204: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0205: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0206: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0207: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0208: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0209: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0210: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0211: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0212: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0213: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0214: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0215: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0216: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0217: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0218: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0219: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0220: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0221: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0222: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0223: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0224: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0225: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0226: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0227: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0228: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0229: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0230: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0231: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0232: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0233: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0234: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0235: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0236: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0237: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0238: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0239: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0240: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0241: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0242: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0243: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0244: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0245: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0246: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0247: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0248: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0249: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0250: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0251: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0252: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0253: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0254: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0255: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0256: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0257: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0258: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0259: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference binary_search_h 0260: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
