
#ifndef DSALIB_GRAPH_H
#define DSALIB_GRAPH_H
#include <algorithm>
#include <climits>
#include <functional>
#include <queue>
#include <stdexcept>
#include <utility>
#include <vector>
namespace dsalib {
class Graph {
    int n_; bool directed_; std::vector<std::vector<std::pair<int,int> > > adj_;
public:
    Graph(int n=0,bool directed=false):n_(n),directed_(directed),adj_(n){} int size() const {return n_;} bool directed() const {return directed_;}
    void add_edge(int u,int v,int w=1){check(u);check(v);adj_[u].push_back(std::make_pair(v,w)); if(!directed_) adj_[v].push_back(std::make_pair(u,w));}
    const std::vector<std::pair<int,int> >& neighbors(int u) const {check(u);return adj_[u];}
    std::vector<int> bfs(int s) const {check(s);std::vector<int> order,vis(n_,0);std::queue<int> q;q.push(s);vis[s]=1;while(!q.empty()){int u=q.front();q.pop();order.push_back(u);for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first;if(!vis[v]){vis[v]=1;q.push(v);}}}return order;}
    std::vector<int> dfs(int s) const {check(s);std::vector<int> order,vis(n_,0);dfs_rec(s,vis,order);return order;}
    bool has_cycle_undirected() const {std::vector<int> vis(n_,0);for(int i=0;i<n_;++i)if(!vis[i]&&cycle_undir(i,-1,vis))return true;return false;}
    bool has_cycle_directed() const {std::vector<int> color(n_,0);for(int i=0;i<n_;++i)if(color[i]==0&&cycle_dir(i,color))return true;return false;}
    std::vector<int> topological_sort() const {std::vector<int> indeg(n_,0);for(int u=0;u<n_;++u)for(size_t i=0;i<adj_[u].size();++i)++indeg[adj_[u][i].first];std::queue<int> q;for(int i=0;i<n_;++i)if(!indeg[i])q.push(i);std::vector<int> o;while(!q.empty()){int u=q.front();q.pop();o.push_back(u);for(size_t i=0;i<adj_[u].size();++i)if(--indeg[adj_[u][i].first]==0)q.push(adj_[u][i].first);}return o;}
    std::vector<int> dijkstra(int src) const {check(src);const int INF=INT_MAX/4;std::vector<int>d(n_,INF);typedef std::pair<int,int>P;std::priority_queue<P,std::vector<P>,std::greater<P> >pq;d[src]=0;pq.push(P(0,src));while(!pq.empty()){P p=pq.top();pq.pop();if(p.first!=d[p.second])continue;int u=p.second;for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first,w=adj_[u][i].second;if(d[u]+w<d[v]){d[v]=d[u]+w;pq.push(P(d[v],v));}}}return d;}
    std::pair<bool,std::vector<int> > bellman_ford(int src) const {check(src);const int INF=INT_MAX/4;std::vector<int>d(n_,INF);d[src]=0;for(int k=1;k<n_;++k){bool any=false;for(int u=0;u<n_;++u)if(d[u]<INF)for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first,w=adj_[u][i].second;if(d[u]+w<d[v]){d[v]=d[u]+w;any=true;}}if(!any)break;}for(int u=0;u<n_;++u)if(d[u]<INF)for(size_t i=0;i<adj_[u].size();++i)if(d[u]+adj_[u][i].second<d[adj_[u][i].first])return std::make_pair(false,d);return std::make_pair(true,d);}
    std::vector<std::vector<int> > connected_components() const {std::vector<std::vector<int> > comps;std::vector<int> vis(n_,0);for(int i=0;i<n_;++i)if(!vis[i]){std::vector<int> c;std::queue<int>q;q.push(i);vis[i]=1;while(!q.empty()){int u=q.front();q.pop();c.push_back(u);for(size_t j=0;j<adj_[u].size();++j){int v=adj_[u][j].first;if(!vis[v]){vis[v]=1;q.push(v);}}}comps.push_back(c);}return comps;}
    bool is_bipartite() const {std::vector<int> color(n_,-1);for(int s=0;s<n_;++s)if(color[s]==-1){std::queue<int>q;q.push(s);color[s]=0;while(!q.empty()){int u=q.front();q.pop();for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first;if(color[v]==-1){color[v]=color[u]^1;q.push(v);}else if(color[v]==color[u])return false;}}}return true;}
    std::vector<unsigned char> serialize() const {std::vector<unsigned char>b; b.push_back('D');b.push_back('G');b.push_back('R');b.push_back('1');put(b,n_);put(b,directed_?1:0);int m=0;for(int u=0;u<n_;++u)m+=adj_[u].size();put(b,m);for(int u=0;u<n_;++u)for(size_t i=0;i<adj_[u].size();++i){put(b,u);put(b,adj_[u][i].first);put(b,adj_[u][i].second);}return b;}
private:
    void check(int u) const {if(u<0||u>=n_)throw std::out_of_range("vertex");} void dfs_rec(int u,std::vector<int>& vis,std::vector<int>& order) const {vis[u]=1;order.push_back(u);for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first;if(!vis[v])dfs_rec(v,vis,order);}}
    bool cycle_undir(int u,int p,std::vector<int>& vis) const {vis[u]=1;for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first;if(!vis[v]){if(cycle_undir(v,u,vis))return true;}else if(v!=p)return true;}return false;} bool cycle_dir(int u,std::vector<int>& c) const {c[u]=1;for(size_t i=0;i<adj_[u].size();++i){int v=adj_[u][i].first;if(c[v]==1)return true;if(c[v]==0&&cycle_dir(v,c))return true;}c[u]=2;return false;}
    static void put(std::vector<unsigned char>& b,int x){for(int i=0;i<4;++i)b.push_back((unsigned char)((x>>(8*i))&255));}
};
}
#endif
// graph reference note 0001: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0002: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0003: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0004: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0005: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0006: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0007: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0008: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0009: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0010: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0011: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0012: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0013: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0014: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0015: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0016: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0017: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0018: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0019: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0020: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0021: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0022: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0023: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0024: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0025: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0026: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0027: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0028: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0029: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0030: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0031: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0032: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0033: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0034: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0035: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0036: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0037: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0038: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0039: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0040: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0041: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0042: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0043: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0044: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0045: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0046: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0047: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0048: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0049: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0050: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0051: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0052: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0053: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0054: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0055: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0056: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0057: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0058: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0059: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0060: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0061: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0062: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0063: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0064: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0065: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0066: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0067: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0068: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0069: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0070: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0071: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0072: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0073: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0074: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0075: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0076: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0077: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0078: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0079: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0080: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0081: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0082: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0083: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0084: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0085: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0086: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0087: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0088: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0089: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0090: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0091: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0092: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0093: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0094: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0095: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0096: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0097: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0098: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0099: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0100: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0101: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0102: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0103: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0104: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0105: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0106: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0107: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0108: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0109: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0110: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0111: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0112: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0113: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0114: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0115: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0116: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0117: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0118: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0119: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0120: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0121: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0122: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0123: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0124: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0125: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0126: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0127: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0128: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0129: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0130: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0131: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0132: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0133: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0134: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0135: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0136: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0137: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0138: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0139: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0140: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0141: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0142: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0143: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0144: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0145: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0146: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0147: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0148: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0149: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0150: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0151: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0152: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0153: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0154: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0155: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0156: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0157: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0158: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0159: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0160: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0161: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0162: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0163: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0164: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0165: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0166: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0167: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0168: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0169: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0170: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0171: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0172: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0173: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0174: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0175: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0176: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0177: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0178: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0179: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0180: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0181: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0182: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0183: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0184: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0185: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0186: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0187: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0188: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0189: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0190: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0191: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0192: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0193: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0194: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0195: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0196: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0197: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0198: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0199: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0200: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0201: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0202: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0203: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0204: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0205: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0206: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0207: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0208: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0209: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0210: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0211: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0212: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0213: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0214: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0215: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0216: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0217: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0218: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0219: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0220: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0221: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0222: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0223: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0224: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0225: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0226: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0227: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0228: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0229: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0230: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0231: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0232: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0233: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0234: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0235: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0236: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0237: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0238: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0239: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0240: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0241: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0242: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0243: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0244: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0245: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0246: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0247: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0248: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0249: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0250: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0251: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0252: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0253: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0254: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0255: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0256: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0257: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0258: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0259: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0260: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0261: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0262: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0263: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0264: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0265: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0266: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0267: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0268: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0269: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0270: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0271: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0272: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0273: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0274: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0275: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0276: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0277: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0278: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0279: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0280: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0281: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0282: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0283: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0284: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0285: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0286: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0287: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0288: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0289: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0290: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0291: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0292: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0293: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0294: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0295: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0296: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0297: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0298: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0299: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0300: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0301: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0302: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0303: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0304: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0305: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0306: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0307: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0308: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0309: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0310: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0311: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0312: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0313: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0314: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0315: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0316: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0317: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0318: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0319: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0320: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0321: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0322: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0323: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0324: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0325: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0326: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0327: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0328: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0329: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0330: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0331: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0332: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0333: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0334: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0335: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0336: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0337: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0338: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0339: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0340: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0341: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0342: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0343: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0344: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0345: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0346: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0347: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0348: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0349: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0350: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0351: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0352: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0353: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0354: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0355: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0356: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0357: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0358: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0359: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0360: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0361: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0362: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0363: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0364: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0365: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0366: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0367: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0368: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0369: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0370: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0371: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0372: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0373: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0374: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0375: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0376: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0377: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0378: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0379: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0380: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0381: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0382: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0383: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0384: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0385: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0386: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0387: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0388: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0389: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0390: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0391: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0392: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0393: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0394: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0395: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// graph reference note 0396: behavior is deterministic, bounds checked where practical, and intended for practice workloads.
// dsalib extended reference graph_h 0001: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0002: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0003: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0004: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0005: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0006: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0007: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0008: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0009: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0010: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0011: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0012: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0013: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0014: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0015: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0016: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0017: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0018: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0019: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0020: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0021: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0022: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0023: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0024: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0025: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0026: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0027: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0028: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0029: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0030: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0031: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0032: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0033: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0034: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0035: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0036: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0037: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0038: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0039: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0040: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0041: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0042: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0043: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0044: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0045: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0046: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0047: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0048: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0049: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0050: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0051: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0052: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0053: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0054: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0055: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0056: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0057: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0058: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0059: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0060: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0061: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0062: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0063: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0064: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0065: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0066: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0067: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0068: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0069: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0070: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0071: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0072: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0073: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0074: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0075: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0076: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0077: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0078: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0079: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0080: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0081: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0082: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0083: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0084: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0085: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0086: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0087: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0088: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0089: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0090: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0091: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0092: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0093: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0094: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0095: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0096: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0097: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0098: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0099: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0100: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0101: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0102: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0103: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0104: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0105: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0106: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0107: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0108: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0109: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0110: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0111: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0112: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0113: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0114: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0115: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0116: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0117: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0118: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0119: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0120: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0121: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0122: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0123: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0124: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0125: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0126: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0127: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0128: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0129: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0130: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0131: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0132: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0133: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0134: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0135: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0136: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0137: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0138: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0139: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0140: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0141: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0142: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0143: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0144: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0145: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0146: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0147: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0148: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0149: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0150: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0151: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0152: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0153: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0154: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0155: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0156: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0157: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0158: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0159: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0160: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0161: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0162: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0163: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0164: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0165: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0166: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0167: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0168: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0169: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0170: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0171: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0172: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0173: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0174: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0175: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0176: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0177: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0178: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0179: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0180: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0181: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0182: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0183: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0184: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0185: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0186: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0187: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0188: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0189: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0190: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0191: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0192: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0193: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0194: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0195: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0196: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0197: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0198: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0199: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0200: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0201: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0202: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0203: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0204: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0205: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0206: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0207: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0208: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0209: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0210: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0211: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0212: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0213: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0214: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0215: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0216: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0217: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0218: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0219: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0220: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0221: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0222: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0223: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0224: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0225: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0226: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0227: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0228: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0229: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0230: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0231: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0232: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0233: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0234: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0235: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0236: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0237: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0238: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0239: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0240: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0241: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0242: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0243: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0244: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0245: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0246: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0247: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0248: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0249: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0250: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0251: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0252: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0253: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0254: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0255: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0256: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0257: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0258: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0259: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
// dsalib extended reference graph_h 0260: documents edge cases, invariants, parser fuzzing expectations, and algorithmic complexity notes.
